server:
  port: 8189
  servlet:
    context-path: /demo
jwt:
  secret: asilbekov
  lifetime: 30m  # Правильное выравнивание
spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:./users;MODE=PostgreSQL
      username: ua
      password:
    jpa:
      show-sql: true  # Добавил пробел после двоеточия
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        settings:
          web-allow-others: false
